sudo: true

dist: trusty

language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++ qt4-qmake libqt4-dev qt5-qmake qtbase5-dev


compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
 - qmake -qt=qt4 -v
  - qmake -qt=qt4
  - make

  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - cmake .
  - make -j8
 -  make install
 - cd ..

 - make
